<?php
declare(strict_types=1);

namespace App\Services;

final class Translator
{
    /**
     * On garde un traducteur volontairement simple :
     * - 2 langues
     * - un dictionnaire PHP local
     * - aucune dependance externe
     *
     * Le but ici est de rendre la preference "language" visible
     * sans introduire tout de suite une couche i18n plus lourde.
     */
    private string $locale;

    private const DICTIONARY = [
        'fr' => [
            'nav_profile' => 'Profil',
            'nav_publish' => 'Publier',
            'nav_friends' => 'Amis',
            'nav_messages' => 'Messages',
            'nav_notifications' => 'Notifications',
            'nav_search' => 'Recherche',
            'nav_admin' => 'Administration',
            'nav_more' => 'Plus',
            'nav_contact' => 'Contact',
            'nav_privacy' => 'Confidentialite',
            'nav_settings' => 'Parametres',
            'nav_logout' => 'Se deconnecter',
            'footer_rights' => 'BOXING Social tout droit reserve',
            'home_title' => 'Accueil',
            'home_heading' => 'Accueil',
            'home_intro' => 'Retrouve rapidement une personne, une publication ou un sujet de discussion.',
            'home_search_placeholder' => 'Rechercher un pseudo ou une publication',
            'home_search_button' => 'Rechercher',
            'settings_title' => 'Parametres',
            'settings_eyebrow' => 'Parametres',
            'settings_heading' => 'Preferences de compte',
            'settings_intro' => 'Regle ici les preferences generales de ton experience sur le reseau social.',
            'settings_general' => 'General',
            'settings_table_missing' => 'La sauvegarde est en attente. Lance d abord la migration SQL migrations/2026_03_13_create_user_settings.sql.',
            'settings_theme' => 'Theme',
            'settings_language' => 'Langue',
            'settings_parental_controls' => 'Controles parentaux',
            'settings_notifications' => 'Notifications',
            'settings_theme_system' => 'Systeme',
            'settings_theme_light' => 'Clair',
            'settings_theme_dark' => 'Sombre',
            'settings_language_french' => 'Francais',
            'settings_language_english' => 'Anglais',
            'common_yes' => 'Oui',
            'common_no' => 'Non',
            'settings_save' => 'Enregistrer les preferences',
            'settings_saved' => 'Parametres mis a jour.',
            'profile_title' => 'Profil',
            'profile_heading' => 'Mon profil',
            'profile_id' => 'ID',
            'profile_role' => 'Role',
            'profile_save' => 'Enregistrer',
            'profile_avatar_heading' => 'Photo de profil',
            'profile_avatar_alt' => 'Avatar',
            'profile_avatar_update' => 'Mettre a jour la photo',
            'profile_password_heading' => 'Changer le mot de passe',
            'profile_password_current' => 'Mot de passe actuel',
            'profile_password_new' => 'Nouveau mot de passe',
            'profile_password_confirm' => 'Confirmer le nouveau mot de passe',
            'profile_password_update' => 'Mettre a jour le mot de passe',
            'public_profile_title' => 'Profil public',
            'public_profile_eyebrow' => 'Profil public',
            'public_profile_member_since' => 'Membre depuis',
            'public_profile_add_friend' => 'Ajouter en ami',
            'public_profile_send_message' => 'Envoyer un message',
            'public_profile_bio' => 'Bio',
            'public_profile_bio_empty' => 'Cette personne n a pas encore renseigne sa bio.',
            'public_profile_public_posts' => 'Publications publiques',
            'public_profile_post_count' => 'publication(s)',
            'public_profile_empty_posts' => 'Aucune publication publique pour le moment.',
            'post_untitled' => 'Publication sans titre',
            'post_image_alt' => 'Image de publication',
            'post_location' => 'Lieu',
            'pagination_previous' => 'Page precedente',
            'pagination_next' => 'Page suivante',
            'pagination_label' => 'Page',
            'posts_title' => 'Fil des publications',
            'posts_heading' => 'Dernieres publications',
            'posts_empty' => 'Aucun post pour le moment.',
            'posts_author' => 'Auteur',
            'posts_edit' => 'Modifier',
            'posts_delete' => 'Supprimer',
            'posts_delete_confirm' => 'Supprimer ce post ?',
            'posts_likes' => 'J aime',
            'posts_like_add' => 'J aime',
            'posts_like_remove' => 'Retirer mon j aime',
            'posts_comments' => 'Commentaires',
            'posts_no_comments' => 'Aucun commentaire.',
            'posts_delete_comment' => 'Supprimer commentaire',
            'posts_add_comment' => 'Ajouter un commentaire...',
            'posts_comment_button' => 'Commenter',
            'posts_view' => 'Voir la publication',
            'posts_create_title' => 'Creer un post',
            'posts_create_heading' => 'Creer un post',
            'posts_title_placeholder' => 'Titre (optionnel)',
            'posts_content_placeholder' => 'Contenu du post',
            'posts_location_placeholder' => 'Lieu (optionnel)',
            'visibility_public' => 'Public',
            'visibility_friends' => 'Amis',
            'visibility_private' => 'Prive',
            'posts_publish' => 'Publier',
            'posts_edit_title' => 'Modifier post',
            'posts_edit_heading' => 'Modifier post',
            'posts_save' => 'Enregistrer',
            'post_show_title' => 'Publication',
            'post_by' => 'Par',
            'post_created_at' => 'Creee le',
            'post_visibility' => 'Visibilite',
            'post_no_comments_yet' => 'Aucun commentaire pour le moment.',
            'post_delete_own_comment' => 'Supprimer mon commentaire',
            'friends_title' => 'Amis',
            'friends_heading' => 'Gestion des amis',
            'friends_send_request' => 'Envoyer une demande',
            'friends_username_placeholder' => 'Pseudo de la personne',
            'friends_send' => 'Envoyer',
            'friends_incoming' => 'Demandes recues',
            'friends_incoming_empty' => 'Aucune demande recue.',
            'friends_wants_friend' => 'veut etre ton ami.',
            'friends_accept' => 'Accepter',
            'friends_decline' => 'Refuser',
            'friends_outgoing' => 'Demandes envoyees',
            'friends_outgoing_empty' => 'Aucune demande envoyee.',
            'friends_pending' => 'En attente',
            'friends_my_friends' => 'Mes amis',
            'friends_empty' => 'Tu n as pas encore d amis.',
            'admin_title' => 'Administration',
            'admin_heading' => 'Tableau de bord administration',
            'admin_users' => 'Utilisateurs',
            'admin_email' => 'Email',
            'admin_role' => 'Role',
            'admin_status' => 'Etat',
            'admin_action' => 'Action',
            'admin_active' => 'actif',
            'admin_disabled' => 'desactive',
            'admin_disable' => 'Desactiver',
            'admin_enable' => 'Activer',
            'admin_posts' => 'Publications',
            'admin_author' => 'Auteur',
            'admin_title_column' => 'Titre',
            'admin_visibility' => 'Visibilite',
            'admin_delete_post_confirm' => 'Supprimer ce post ?',
            'admin_delete' => 'Supprimer',
            'admin_comments' => 'Commentaires',
            'admin_post' => 'Publication',
            'admin_content' => 'Contenu',
            'admin_delete_comment_confirm' => 'Supprimer ce commentaire ?',
            'admin_log' => 'Journal administration',
            'admin_log_empty' => 'Aucune action admin.',
            'admin_date' => 'Date',
            'admin_administrator' => 'Administrateur',
            'admin_target' => 'Cible',
            'admin_log_note' => 'Historique des actions sensibles pour audit.',
            'contact_title' => 'Contact',
            'contact_eyebrow' => 'Contact',
            'contact_heading' => 'Entrer en contact avec Boxing Social',
            'contact_intro' => 'Une question sur la communaute, un signalement ou un besoin d aide sur le reseau social. Utilise ce formulaire pour nous ecrire.',
            'contact_email' => 'Email',
            'contact_subject' => 'Sujet',
            'contact_message' => 'Message',
            'contact_subject_general' => 'Question generale',
            'contact_subject_support' => 'Support technique',
            'contact_subject_report' => 'Signalement',
            'contact_message_placeholder' => 'Explique ton besoin...',
            'contact_send' => 'Envoyer',
            'privacy_title' => 'Politique de confidentialite',
            'privacy_eyebrow' => 'Confidentialite',
            'privacy_heading' => 'Politique de Confidentialite et Conditions Generales',
            'privacy_intro' => 'Version de travail pour cadrer les contenus legaux du site avant la version finale.',
            'privacy_article_1_title' => 'Article 1 : Objet',
            'privacy_article_1_text' => 'Cette page presente les regles generales d utilisation de Boxing Social ainsi que les principes de traitement des donnees personnelles.',
            'privacy_article_2_title' => 'Article 2 : Donnees collectees',
            'privacy_article_2_text' => 'Les donnees de compte, de publication, de messagerie et d interaction sont stockees pour assurer le fonctionnement du reseau social.',
            'privacy_article_3_title' => 'Article 3 : Usage des donnees',
            'privacy_article_3_text' => 'Les informations sont utilisees pour l authentification, la moderation, la messagerie, les notifications et la personnalisation de l experience.',
            'privacy_article_4_title' => 'Article 4 : Droits utilisateur',
            'privacy_article_4_text' => 'Chaque utilisateur peut demander la correction, la suppression ou l export de ses donnees selon les modalites qui seront precisees sur la version finale.',
            'privacy_article_5_title' => 'Article 5 : Contact',
            'privacy_article_5_text' => 'Pour toute demande liee a la confidentialite, la page de contact servira de point d entree fonctionnel.',
        ],
        'en' => [
            'nav_profile' => 'Profile',
            'nav_publish' => 'Publish',
            'nav_friends' => 'Friends',
            'nav_messages' => 'Messages',
            'nav_notifications' => 'Notifications',
            'nav_search' => 'Search',
            'nav_admin' => 'Admin',
            'nav_more' => 'More',
            'nav_contact' => 'Contact',
            'nav_privacy' => 'Privacy',
            'nav_settings' => 'Settings',
            'nav_logout' => 'Log out',
            'footer_rights' => 'BOXING Social all rights reserved',
            'home_title' => 'Home',
            'home_heading' => 'Home',
            'home_intro' => 'Quickly find a person, a post or a discussion topic.',
            'home_search_placeholder' => 'Search for a username or a post',
            'home_search_button' => 'Search',
            'settings_title' => 'Settings',
            'settings_eyebrow' => 'Settings',
            'settings_heading' => 'Account preferences',
            'settings_intro' => 'Adjust the general preferences of your social network experience here.',
            'settings_general' => 'General',
            'settings_table_missing' => 'Saving is pending. Run the SQL migration migrations/2026_03_13_create_user_settings.sql first.',
            'settings_theme' => 'Theme',
            'settings_language' => 'Language',
            'settings_parental_controls' => 'Parental controls',
            'settings_notifications' => 'Notifications',
            'settings_theme_system' => 'System',
            'settings_theme_light' => 'Light',
            'settings_theme_dark' => 'Dark',
            'settings_language_french' => 'French',
            'settings_language_english' => 'English',
            'common_yes' => 'Yes',
            'common_no' => 'No',
            'settings_save' => 'Save preferences',
            'settings_saved' => 'Settings updated.',
            'profile_title' => 'Profile',
            'profile_heading' => 'My profile',
            'profile_id' => 'ID',
            'profile_role' => 'Role',
            'profile_save' => 'Save',
            'profile_avatar_heading' => 'Profile picture',
            'profile_avatar_alt' => 'Avatar',
            'profile_avatar_update' => 'Update picture',
            'profile_password_heading' => 'Change password',
            'profile_password_current' => 'Current password',
            'profile_password_new' => 'New password',
            'profile_password_confirm' => 'Confirm new password',
            'profile_password_update' => 'Update password',
            'public_profile_title' => 'Public profile',
            'public_profile_eyebrow' => 'Public profile',
            'public_profile_member_since' => 'Member since',
            'public_profile_add_friend' => 'Add friend',
            'public_profile_send_message' => 'Send message',
            'public_profile_bio' => 'Bio',
            'public_profile_bio_empty' => 'This person has not filled in a bio yet.',
            'public_profile_public_posts' => 'Public posts',
            'public_profile_post_count' => 'post(s)',
            'public_profile_empty_posts' => 'No public posts for now.',
            'post_untitled' => 'Untitled post',
            'post_image_alt' => 'Post image',
            'post_location' => 'Location',
            'pagination_previous' => 'Previous page',
            'pagination_next' => 'Next page',
            'pagination_label' => 'Page',
            'posts_title' => 'Posts feed',
            'posts_heading' => 'Latest posts',
            'posts_empty' => 'No posts for now.',
            'posts_author' => 'Author',
            'posts_edit' => 'Edit',
            'posts_delete' => 'Delete',
            'posts_delete_confirm' => 'Delete this post?',
            'posts_likes' => 'Likes',
            'posts_like_add' => 'Like',
            'posts_like_remove' => 'Remove my like',
            'posts_comments' => 'Comments',
            'posts_no_comments' => 'No comments.',
            'posts_delete_comment' => 'Delete comment',
            'posts_add_comment' => 'Add a comment...',
            'posts_comment_button' => 'Comment',
            'posts_view' => 'View post',
            'posts_create_title' => 'Create a post',
            'posts_create_heading' => 'Create a post',
            'posts_title_placeholder' => 'Title (optional)',
            'posts_content_placeholder' => 'Post content',
            'posts_location_placeholder' => 'Location (optional)',
            'visibility_public' => 'Public',
            'visibility_friends' => 'Friends',
            'visibility_private' => 'Private',
            'posts_publish' => 'Publish',
            'posts_edit_title' => 'Edit post',
            'posts_edit_heading' => 'Edit post',
            'posts_save' => 'Save',
            'post_show_title' => 'Post',
            'post_by' => 'By',
            'post_created_at' => 'Created on',
            'post_visibility' => 'Visibility',
            'post_no_comments_yet' => 'No comments yet.',
            'post_delete_own_comment' => 'Delete my comment',
            'friends_title' => 'Friends',
            'friends_heading' => 'Friends management',
            'friends_send_request' => 'Send a request',
            'friends_username_placeholder' => 'Username of the person',
            'friends_send' => 'Send',
            'friends_incoming' => 'Incoming requests',
            'friends_incoming_empty' => 'No incoming requests.',
            'friends_wants_friend' => 'wants to be your friend.',
            'friends_accept' => 'Accept',
            'friends_decline' => 'Decline',
            'friends_outgoing' => 'Sent requests',
            'friends_outgoing_empty' => 'No sent requests.',
            'friends_pending' => 'Pending',
            'friends_my_friends' => 'My friends',
            'friends_empty' => 'You do not have any friends yet.',
            'admin_title' => 'Admin',
            'admin_heading' => 'Admin dashboard',
            'admin_users' => 'Users',
            'admin_email' => 'Email',
            'admin_role' => 'Role',
            'admin_status' => 'Status',
            'admin_action' => 'Action',
            'admin_active' => 'active',
            'admin_disabled' => 'disabled',
            'admin_disable' => 'Disable',
            'admin_enable' => 'Enable',
            'admin_posts' => 'Posts',
            'admin_author' => 'Author',
            'admin_title_column' => 'Title',
            'admin_visibility' => 'Visibility',
            'admin_delete_post_confirm' => 'Delete this post?',
            'admin_delete' => 'Delete',
            'admin_comments' => 'Comments',
            'admin_post' => 'Post',
            'admin_content' => 'Content',
            'admin_delete_comment_confirm' => 'Delete this comment?',
            'admin_log' => 'Admin log',
            'admin_log_empty' => 'No admin actions.',
            'admin_date' => 'Date',
            'admin_administrator' => 'Administrator',
            'admin_target' => 'Target',
            'admin_log_note' => 'History of sensitive actions for audit.',
            'contact_title' => 'Contact',
            'contact_eyebrow' => 'Contact',
            'contact_heading' => 'Get in touch with Boxing Social',
            'contact_intro' => 'A community question, a report or help needed on the social network. Use this form to contact us.',
            'contact_email' => 'Email',
            'contact_subject' => 'Subject',
            'contact_message' => 'Message',
            'contact_subject_general' => 'General question',
            'contact_subject_support' => 'Technical support',
            'contact_subject_report' => 'Report',
            'contact_message_placeholder' => 'Explain what you need...',
            'contact_send' => 'Send',
            'privacy_title' => 'Privacy policy',
            'privacy_eyebrow' => 'Privacy',
            'privacy_heading' => 'Privacy Policy and General Terms',
            'privacy_intro' => 'Working draft used to frame the legal content of the site before the final version.',
            'privacy_article_1_title' => 'Article 1: Purpose',
            'privacy_article_1_text' => 'This page presents the general rules for using Boxing Social as well as the principles for processing personal data.',
            'privacy_article_2_title' => 'Article 2: Data collected',
            'privacy_article_2_text' => 'Account, publication, messaging and interaction data are stored to ensure the social network works correctly.',
            'privacy_article_3_title' => 'Article 3: Use of data',
            'privacy_article_3_text' => 'Information is used for authentication, moderation, messaging, notifications and personalizing the experience.',
            'privacy_article_4_title' => 'Article 4: User rights',
            'privacy_article_4_text' => 'Each user may request correction, deletion or export of their data according to the terms that will be specified in the final version.',
            'privacy_article_5_title' => 'Article 5: Contact',
            'privacy_article_5_text' => 'For any privacy-related request, the contact page serves as the functional entry point.',
        ],
    ];

    public function __construct(string $language = 'francais')
    {
        $this->locale = $language === 'anglais' ? 'en' : 'fr';
    }

    public function htmlLang(): string
    {
        return $this->locale;
    }

    public function text(string $key): string
    {
        return self::DICTIONARY[$this->locale][$key]
            ?? self::DICTIONARY['fr'][$key]
            ?? $key;
    }
}
